spring:
  datasource:
    username: root
    password: 2saltedsun
    url: jdbc:mysql://localhost:3306/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: "classpath:/mapper/**/*.xml" # mapper文件所在位置
  global-config:
    db-config:
      id-type: auto # 主键自增, 无需手动设置对象id

server:
  port: 7000


